name:                atsubmit
version:             0.1.0.0
github:              "flow6852/atsubmit"
license:             BSD3
author:              "flow_6852"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/atsubmit#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
          - http-conduit
          - html-conduit
          - xml-conduit
          - http-types
          - text
          - bytestring
          - network
          - directory
          - vector
          - turtle
          - foldl
          - aeson
          - transformers
          - uri-encode
          - unbounded-delays
          - containers
          - filepath
          - string-conversions
executables:
  atsubmit-server:
    when:
    - condition: 'os(windows)'
      then:
        main: server-win.hs
      else:
        main: server-linux.hs
        dependencies:
        - hdaemonize
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atsubmit
    - text
    - vector
    - bytestring
    - directory
    - uri-encode
    - filepath
  atsubmit-client:
    main:                client.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atsubmit
    - text
    - vector
    - bytestring
    - directory
    - uri-encode
    - filepath
    - terminal-size

tests:
  atsubmit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - atsubmit
    - text
    - vector
    - directory
    - bytestring
    - filepath
    when:
      - condition: '!os(windows)'
        dependencies:
          - hdaemonize
